from typing import Dict

# Mapping different representations to a standard license name
license_mapping = {
    "MIT": "MIT",
    "MIT License": "MIT",
    "MIT License (Expat)": "MIT",
    "Apache 2.0": "Apache-2.0",
    "Apache License 2.0": "Apache-2.0",
    "BSD 3-Clause": "BSD-3-Clause",
    "BSD 3-Clause \"New\" or \"Revised\"": "BSD-3-Clause",
    "BSD License": "BSD-3-Clause",
    "GPL-3.0": "GPLv3",
    "GNU General Public License v3.0": "GPLv3",
    "GNU General Public License version 3.0": "GPLv3",
    "GNU GPL v3": "GPLv3",
    "GPLv3": "GPLv3",
    "LGPL-3.0": "LGPL-3.0",
    "GNU Lesser General Public License v3.0": "LGPL-3.0",
    "GNU LGPL v3": "LGPL-3.0",
    "Mozilla Public License 2.0": "MPL-2.0",
    "MPL 2.0": "MPL-2.0",
    "AGPL-3.0": "AGPL-3.0",
    "Affero General Public License v3.0": "AGPL-3.0",
    "GNU Affero General Public License v3.0": "AGPL-3.0",
    "AGPLv3": "AGPL-3.0",
    "EPL-2.0": "EPL-2.0",
    "Eclipse Public License 2.0": "EPL-2.0",
    "Unlicense": "Unlicense",
    "Public Domain": "Unlicense",
    "Unlicense (Public Domain Dedication)": "Unlicense",
    "ISC": "ISC",
    "Internet Systems Consortium License": "ISC",
    "-": "Undefined",
    "Other": "Undefined",
    "other": "Undefined",
    "": "Undefined",
}


# Compatibility matrix
compatibility_matrix: Dict[str, Dict[str, bool]] = {
    "MIT": {
        "MIT": True, 
        "Apache-2.0": True, 
        "BSD-3-Clause": True, 
        "MPL-2.0": True, 
        "GPLv3": False, 
        "LGPL-3.0": False, 
        "AGPL-3.0": False, 
        "EPL-2.0": True, 
        "Unlicense": True,
        "ISC": True,
    },
    "Apache-2.0": {
        "MIT": True, 
        "Apache-2.0": True, 
        "BSD-3-Clause": True, 
        "MPL-2.0": True, 
        "GPLv3": False, 
        "LGPL-3.0": False, 
        "AGPL-3.0": False, 
        "EPL-2.0": True, 
        "Unlicense": False,
        "ISC": True,
    },
    "BSD-3-Clause": {
        "MIT": True, 
        "Apache-2.0": True, 
        "BSD-3-Clause": True, 
        "MPL-2.0": True, 
        "GPLv3": False, 
        "LGPL-3.0": False, 
        "AGPL-3.0": False, 
        "EPL-2.0": True, 
        "Unlicense": True,
        "ISC": True,
    },
    "MPL-2.0": {
        "MIT": True, 
        "Apache-2.0": True, 
        "BSD-3-Clause": True, 
        "MPL-2.0": True, 
        "GPLv3": False, 
        "LGPL-3.0": False, 
        "AGPL-3.0": False, 
        "EPL-2.0": True, 
        "Unlicense": False,
        "ISC": True,
    },
    "GPLv3": {
        "MIT": False, 
        "Apache-2.0": False, 
        "BSD-3-Clause": False, 
        "MPL-2.0": False, 
        "GPLv3": True, 
        "LGPL-3.0": True, 
        "AGPL-3.0": True, 
        "EPL-2.0": False, 
        "Unlicense": False,
        "ISC": False,
    },
    "LGPL-3.0": {
        "MIT": False, 
        "Apache-2.0": False, 
        "BSD-3-Clause": False, 
        "MPL-2.0": False, 
        "GPLv3": True, 
        "LGPL-3.0": True, 
        "AGPL-3.0": False, 
        "EPL-2.0": False, 
        "Unlicense": False,
        "ISC": False,
    },
    "AGPL-3.0": {
        "MIT": False, 
        "Apache-2.0": False, 
        "BSD-3-Clause": False, 
        "MPL-2.0": False, 
        "GPLv3": True, 
        "LGPL-3.0": False, 
        "AGPL-3.0": True, 
        "EPL-2.0": False, 
        "Unlicense": False,
        "ISC": False,
    },
    "EPL-2.0": {
        "MIT": True, 
        "Apache-2.0": True, 
        "BSD-3-Clause": True, 
        "MPL-2.0": True, 
        "GPLv3": False, 
        "LGPL-3.0": False, 
        "AGPL-3.0": False, 
        "EPL-2.0": True, 
        "Unlicense": False,
        "ISC": True,
    },
    "Unlicense": {
        "MIT": True, 
        "Apache-2.0": False, 
        "BSD-3-Clause": True, 
        "MPL-2.0": False, 
        "GPLv3": False, 
        "LGPL-3.0": False, 
        "AGPL-3.0": False, 
        "EPL-2.0": False, 
        "Unlicense": True,
        "ISC": True,
    },
    "ISC": {
        "MIT": True, 
        "Apache-2.0": True, 
        "BSD-3-Clause": True, 
        "MPL-2.0": True, 
        "GPLv3": False, 
        "LGPL-3.0": False, 
        "AGPL-3.0": False, 
        "EPL-2.0": True, 
        "Unlicense": True,
        "ISC": True,
    },
}

