name: Describe Dependencies

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  describe-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Describe Dependencies
      run: |
        node -e "const fs = require('fs'); const sbom = JSON.parse(fs.readFileSync('sbom.json', 'utf8')); const dependencies = sbom.components.map(c => ({ name: c.name, version: c.version, license: c.license, authors: c.authors.map(a => a.name).join(', ') })); fs.writeFileSync('dependencies.json', JSON.stringify(dependencies, null, 2));"
    
    - name: Upload Dependencies JSON
      uses: actions/upload-artifact@v2
      with:
        name: dependencies
        path: dependencies.json
