name: Release

on:
  push:
    branches:
      - main  # Trigger release on pushes to the main branch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Retrieve Release Notes
        id: release_notes
        run: echo "::set-output name=notes::$(npx semantic-release --print-config)"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: path/to/artifacts/*.zip
          body: ${{ steps.release_notes.outputs.notes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
