name: Generate SPDX Document

on:
  push:
    branches:
      - main

jobs:
  generate-spdx:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.13'

      - name: Ensure SPDX configuration file exists
        run: |
          if [ ! -f .spdx-builder.yml ]; then
            echo "SPDX configuration file not found!"
            exit 1
          fi

      - name: Create SPDX file
        id: spdx-builder
        uses: philips-software/spdx-action@v0.9.1.1
        with:
          project: searchSECO-miner
          mode: ort

      - name: Upload SPDX document
        uses: actions/upload-artifact@v2
        with:
          name: spdx-document
          path: ${{ steps.spdx-builder.outputs.spdx-file }}
