name: Generate SPDX Document

on:
  push:
    branches:
      - main

jobs:
  generate-spdx:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
  - uses: actions/setup-java@v1
    with:
      java-version: '11.0.13'
- name: Create spdx-file
    id: spdx-builder
    uses: philips-software/spdx-action@v0.9.1.1
    with:
      project: searchSECO-miner
      mode: ort
  - uses: actions/upload-artifact@v2
    with:
      name: licenses
      path: ${{ steps.spdx-builder.outputs.spdx-file }}
      with:
        name: spdx-document
        path: spdx-document.spdx.json
