name: SPDX Generation and Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]

jobs:
  spdx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install SPDX tools
        run: |
          pip install spdx-tools
          pip install spdx-creator

      - name: Generate SPDX Document
        run: |
          spdx-creator --name "searchSECO-miner" --version "1.0.0" --url "https://github.com/SecureSECO/searchSECO-miner" --author "Slinger Jansen" --output spdx-file.spdx

      - name: Validate SPDX Document
        run: |
          spdx-tools verify spdx-file.spdx
